import { Skill, CareerRole, AssessmentQuestion } from '../common/types.js';

export const INITIAL_SKILLS: Skill[] = [
  {
    id: 'skl_dsa',
    name: 'Data Structures & Algorithms',
    category: 'core_cs',
    description: 'Arrays, Trees, Graphs, Sorting, Dynamic Programming and Complexity Analysis',
    maxScore: 100,
  },
  {
    id: 'skl_ts_react',
    name: 'TypeScript & Modern React',
    category: 'frontend',
    description: 'Component architecture, state management, hooks, and static typing in React',
    maxScore: 100,
  },
  {
    id: 'skl_node_express',
    name: 'Node.js & Express Architecture',
    category: 'backend',
    description: 'REST APIs, middleware pipelines, async patterns, and modular monolith design',
    maxScore: 100,
  },
  {
    id: 'skl_db_sql',
    name: 'PostgreSQL & Database Design',
    category: 'backend',
    description: 'Relational modeling, indexing, ACID transactions, normalization, and query tuning',
    maxScore: 100,
  },
  {
    id: 'skl_sys_design',
    name: 'System Design & Scalability',
    category: 'core_cs',
    description: 'Caching, load balancing, message queues, microservices, and database partitioning',
    maxScore: 100,
  },
  {
    id: 'skl_devops_docker',
    name: 'Docker, CI/CD & Cloud Deployments',
    category: 'devops',
    description: 'Containerization, automated build pipelines, container registries, and basic cloud infra',
    maxScore: 100,
  },
];

export const INITIAL_CAREERS: CareerRole[] = [
  {
    id: 'car_fullstack',
    title: 'Full Stack Engineer',
    slug: 'full-stack-engineer',
    description: 'Designs and builds end-to-end web applications with modern frontend and resilient backends.',
    marketDemand: 'very_high',
    averageSalary: '$115,000 - $155,000',
    requiredSkills: [
      { skillId: 'skl_ts_react', skillName: 'TypeScript & Modern React', weight: 0.25, targetLevel: 85 },
      { skillId: 'skl_node_express', skillName: 'Node.js & Express Architecture', weight: 0.25, targetLevel: 85 },
      { skillId: 'skl_db_sql', skillName: 'PostgreSQL & Database Design', weight: 0.20, targetLevel: 80 },
      { skillId: 'skl_dsa', skillName: 'Data Structures & Algorithms', weight: 0.15, targetLevel: 75 },
      { skillId: 'skl_devops_docker', skillName: 'Docker, CI/CD & Cloud Deployments', weight: 0.15, targetLevel: 70 },
    ],
  },
  {
    id: 'car_backend',
    title: 'Backend Systems Engineer',
    slug: 'backend-systems-engineer',
    description: 'Specializes in high-throughput APIs, distributed systems, resilient data pipelines, and database optimization.',
    marketDemand: 'very_high',
    averageSalary: '$120,000 - $165,000',
    requiredSkills: [
      { skillId: 'skl_node_express', skillName: 'Node.js & Express Architecture', weight: 0.30, targetLevel: 90 },
      { skillId: 'skl_db_sql', skillName: 'PostgreSQL & Database Design', weight: 0.30, targetLevel: 90 },
      { skillId: 'skl_sys_design', skillName: 'System Design & Scalability', weight: 0.25, targetLevel: 80 },
      { skillId: 'skl_dsa', skillName: 'Data Structures & Algorithms', weight: 0.15, targetLevel: 80 },
    ],
  },
  {
    id: 'car_frontend',
    title: 'Senior Frontend Architect',
    slug: 'senior-frontend-architect',
    description: 'Focuses on complex web user interfaces, performant rendering, responsive design systems, and client state.',
    marketDemand: 'high',
    averageSalary: '$110,000 - $150,000',
    requiredSkills: [
      { skillId: 'skl_ts_react', skillName: 'TypeScript & Modern React', weight: 0.50, targetLevel: 95 },
      { skillId: 'skl_node_express', skillName: 'Node.js & Express Architecture', weight: 0.20, targetLevel: 70 },
      { skillId: 'skl_dsa', skillName: 'Data Structures & Algorithms', weight: 0.15, targetLevel: 70 },
      { skillId: 'skl_devops_docker', skillName: 'Docker, CI/CD & Cloud Deployments', weight: 0.15, targetLevel: 65 },
    ],
  },
];

// Curated question bank (Initial Assessment is 100% Curated as per Rule 6)
export const CURATED_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'q_ts_01',
    skillId: 'skl_ts_react',
    difficulty: 'medium',
    questionText: 'What is the primary benefit of using `unknown` over `any` in TypeScript for API response validation?',
    options: [
      'unknown prevents you from performing arbitrary operations without explicit type narrowing or casting',
      'unknown turns off all compile-time type checking completely',
      'unknown automatically parses JSON payloads into runtime records',
      'unknown executes faster at runtime than any',
    ],
    correctOptionIndex: 0,
    explanation: 'TypeScript forces developers to perform type checks or narrowing before accessing properties on an unknown type, preventing runtime property access errors.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_ts_02',
    skillId: 'skl_ts_react',
    difficulty: 'medium',
    questionText: 'In React 19, which hook is natively designed to access the value of an asynchronous action or resource directly inside render without repetitive useEffect states?',
    options: [
      'useMemo()',
      'use()',
      'useDeferredValue()',
      'useLayoutEffect()',
    ],
    correctOptionIndex: 1,
    explanation: 'The use() API in React allows reading the resolved value of Promises or context directly in components and integrates with Suspense.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_be_01',
    skillId: 'skl_node_express',
    difficulty: 'medium',
    questionText: 'In Express middleware pipelines, what happens if an error occurs inside an async handler without a try/catch or wrapper?',
    options: [
      'Express automatically catches it and formats a 500 response in Express 4 without any external handling',
      'It triggers an unhandled promise rejection that can crash the Node process or leave the request hanging',
      'It reroutes to the 404 handler immediately',
      'Node restarts the server instantly and retries the request',
    ],
    correctOptionIndex: 1,
    explanation: 'In Express 4, asynchronous errors must either be passed to next(err) explicitly or handled with an async handler wrapper.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_db_01',
    skillId: 'skl_db_sql',
    difficulty: 'medium',
    questionText: 'Which index type in PostgreSQL is best suited for equality and range queries on standard scalar types like integers and timestamps?',
    options: [
      'GIN (Generalized Inverted Index)',
      'B-Tree Index',
      'BRIN (Block Range Index)',
      'Hash Index',
    ],
    correctOptionIndex: 1,
    explanation: 'B-Tree is the default and most versatile index type in PostgreSQL, ideal for comparisons like <, <=, =, >=, and >.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_dsa_01',
    skillId: 'skl_dsa',
    difficulty: 'hard',
    questionText: 'What is the amortized time complexity of inserting n elements into a dynamic array (like JavaScript Array or Python list)?',
    options: [
      'O(n^2)',
      'O(n log n)',
      'O(n)',
      'O(1)',
    ],
    correctOptionIndex: 2,
    explanation: 'While an individual resize copy takes O(k), doubling capacity ensures each element is copied a constant number of times over n insertions, giving O(1) amortized per insert and O(n) total for n inserts.',
    source: 'curated',
    weight: 1.2,
  },
  {
    id: 'q_sys_01',
    skillId: 'skl_sys_design',
    difficulty: 'medium',
    questionText: 'Under the CAP theorem, what does a distributed system sacrifice when it prioritizes Consistency and Partition Tolerance (CP)?',
    options: [
      'Latency',
      'Availability (every non-failing node returns a non-error response)',
      'Durability',
      'Network security',
    ],
    correctOptionIndex: 1,
    explanation: 'During a network partition, a CP system rejects writes or returns errors to preserve consistency rather than returning stale data.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_devops_01',
    skillId: 'skl_devops_docker',
    difficulty: 'easy',
    questionText: 'What is the primary architectural purpose of a multi-stage Docker build in production CI/CD pipelines?',
    options: [
      'To compile dependencies and copy only production artifacts into a minimal runtime image, reducing image size and attack surface',
      'To run multiple independent operating system kernels within a single container',
      'To eliminate the requirement of having Docker daemon running in CI',
      'To automatically scale container replicas horizontally without Kubernetes',
    ],
    correctOptionIndex: 0,
    explanation: 'Multi-stage builds allow isolating heavy compilation tools into intermediate stages and copying only lean release binaries/assets into the final production image.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_devops_02',
    skillId: 'skl_devops_docker',
    difficulty: 'medium',
    questionText: 'In a Dockerfile, why should commands that change less frequently (like package manifests) be copied before commands that change frequently (like source code)?',
    options: [
      'To leverage Docker layer caching and avoid invalidating and reinstalling dependencies on every build',
      'Because Docker cannot copy files located in subdirectories after source code',
      'To enforce file system read-only permissions across all intermediate stages',
      'To ensure environment variables take immediate effect during the container runtime',
    ],
    correctOptionIndex: 0,
    explanation: 'Docker executes Dockerfile instructions from top to bottom and checks its cache for each instruction. Placing stable dependencies first prevents rebuilding cached dependency layers.',
    source: 'curated',
    weight: 1.1,
  },
  {
    id: 'q_db_02',
    skillId: 'skl_db_sql',
    difficulty: 'hard',
    questionText: 'In PostgreSQL, which transaction isolation level guarantees prevention of Dirty Reads, Non-Repeatable Reads, and Phantom Reads without using explicit table locks?',
    options: [
      'Read Committed',
      'Read Uncommitted',
      'Serializable (SSI)',
      'Repeatable Read',
    ],
    correctOptionIndex: 2,
    explanation: 'Serializable Snapshot Isolation (SSI) monitors concurrent read/write dependencies to detect serialization anomalies and aborts transactions to maintain true serializability.',
    source: 'curated',
    weight: 1.3,
  },
  {
    id: 'q_node_02',
    skillId: 'skl_node_express',
    difficulty: 'hard',
    questionText: 'Which phase of the Node.js libuv event loop is responsible for executing setImmediate() callbacks?',
    options: [
      'Timers phase',
      'Check phase',
      'Poll phase',
      'Pending callbacks phase',
    ],
    correctOptionIndex: 1,
    explanation: 'setImmediate() callbacks run in the check phase of the event loop, immediately after the poll phase finishes executing I/O callbacks.',
    source: 'curated',
    weight: 1.2,
  },
  {
    id: 'q_dsa_02',
    skillId: 'skl_dsa',
    difficulty: 'medium',
    questionText: 'When finding a cycle in a singly linked list in O(1) auxiliary space, which algorithmic approach is optimal?',
    options: [
      'Breadth-First Search with a visited hash set',
      'Floyds Tortoise and Hare two-pointer algorithm',
      'Reversing the entire linked list in place',
      'Dijkstras shortest path algorithm',
    ],
    correctOptionIndex: 1,
    explanation: 'Floyds Cycle Detection algorithm uses two pointers moving at different speeds (1 step and 2 steps). If there is a cycle, they meet in O(n) time and O(1) space.',
    source: 'curated',
    weight: 1.1,
  },
  {
    id: 'q_ts_03',
    skillId: 'skl_ts_react',
    difficulty: 'easy',
    questionText: 'In TypeScript, what does the `readonly` modifier on an array property or type (e.g. `readonly string[]`) enforce at compile time?',
    options: [
      'It prevents mutating methods like push, pop, or splice from being called on the array reference',
      'It freezes the underlying JavaScript object in memory at runtime like Object.freeze()',
      'It converts the array into an immutable linked list in JavaScript runtime',
      'It restricts the array to having a maximum length of 1 element',
    ],
    correctOptionIndex: 0,
    explanation: 'readonly in TypeScript is a compile-time assertion that strips mutating methods from the array interface, preventing unintentional side-effects.',
    source: 'curated',
    weight: 0.9,
  },
];
