import { Skill, CareerRole, AssessmentQuestion } from '../common/types.js';

export const INITIAL_SKILLS: Skill[] = [
  {
    id: 'skl_dsa',
    name: 'Data Structures & Algorithms',
    category: 'core_cs',
    description: 'Arrays, Trees, Graphs, Sorting, Dynamic Programming and Complexity Analysis',
    maxScore: 100,
  },
  {
    id: 'skl_ts_react',
    name: 'TypeScript & Modern React',
    category: 'frontend',
    description: 'Component architecture, state management, hooks, and static typing in React',
    maxScore: 100,
  },
  {
    id: 'skl_node_express',
    name: 'Node.js & Express Architecture',
    category: 'backend',
    description: 'REST APIs, middleware pipelines, async patterns, and modular monolith design',
    maxScore: 100,
  },
  {
    id: 'skl_db_sql',
    name: 'PostgreSQL & Database Design',
    category: 'backend',
    description: 'Relational modeling, indexing, ACID transactions, normalization, and query tuning',
    maxScore: 100,
  },
  {
    id: 'skl_sys_design',
    name: 'System Design & Scalability',
    category: 'core_cs',
    description: 'Caching, load balancing, message queues, microservices, and database partitioning',
    maxScore: 100,
  },
  {
    id: 'skl_devops_docker',
    name: 'Docker, CI/CD & Cloud Deployments',
    category: 'devops',
    description: 'Containerization, automated build pipelines, container registries, and basic cloud infra',
    maxScore: 100,
  },
];

export const INITIAL_CAREERS: CareerRole[] = [
  {
    id: 'car_fullstack',
    title: 'Full Stack Engineer',
    slug: 'full-stack-engineer',
    description: 'Designs and builds end-to-end web applications with modern frontend and resilient backends.',
    marketDemand: 'very_high',
    averageSalary: '$115,000 - $155,000',
    requiredSkills: [
      { skillId: 'skl_ts_react', skillName: 'TypeScript & Modern React', weight: 0.25, targetLevel: 85 },
      { skillId: 'skl_node_express', skillName: 'Node.js & Express Architecture', weight: 0.25, targetLevel: 85 },
      { skillId: 'skl_db_sql', skillName: 'PostgreSQL & Database Design', weight: 0.20, targetLevel: 80 },
      { skillId: 'skl_dsa', skillName: 'Data Structures & Algorithms', weight: 0.15, targetLevel: 75 },
      { skillId: 'skl_devops_docker', skillName: 'Docker, CI/CD & Cloud Deployments', weight: 0.15, targetLevel: 70 },
    ],
  },
  {
    id: 'car_backend',
    title: 'Backend Systems Engineer',
    slug: 'backend-systems-engineer',
    description: 'Specializes in high-throughput APIs, distributed systems, resilient data pipelines, and database optimization.',
    marketDemand: 'very_high',
    averageSalary: '$120,000 - $165,000',
    requiredSkills: [
      { skillId: 'skl_node_express', skillName: 'Node.js & Express Architecture', weight: 0.30, targetLevel: 90 },
      { skillId: 'skl_db_sql', skillName: 'PostgreSQL & Database Design', weight: 0.30, targetLevel: 90 },
      { skillId: 'skl_sys_design', skillName: 'System Design & Scalability', weight: 0.25, targetLevel: 80 },
      { skillId: 'skl_dsa', skillName: 'Data Structures & Algorithms', weight: 0.15, targetLevel: 80 },
    ],
  },
  {
    id: 'car_frontend',
    title: 'Senior Frontend Architect',
    slug: 'senior-frontend-architect',
    description: 'Focuses on complex web user interfaces, performant rendering, responsive design systems, and client state.',
    marketDemand: 'high',
    averageSalary: '$110,000 - $150,000',
    requiredSkills: [
      { skillId: 'skl_ts_react', skillName: 'TypeScript & Modern React', weight: 0.50, targetLevel: 95 },
      { skillId: 'skl_node_express', skillName: 'Node.js & Express Architecture', weight: 0.20, targetLevel: 70 },
      { skillId: 'skl_dsa', skillName: 'Data Structures & Algorithms', weight: 0.15, targetLevel: 70 },
      { skillId: 'skl_devops_docker', skillName: 'Docker, CI/CD & Cloud Deployments', weight: 0.15, targetLevel: 65 },
    ],
  },
];

// Curated question bank (Initial Assessment is 100% Curated as per Rule 6)
export const CURATED_QUESTIONS: AssessmentQuestion[] = [
  {
    id: 'q_ts_01',
    skillId: 'skl_ts_react',
    difficulty: 'medium',
    questionText: 'What is the primary benefit of using `unknown` over `any` in TypeScript for API response validation?',
    options: [
      'unknown prevents you from performing arbitrary operations without explicit type narrowing or casting',
      'unknown turns off all compile-time type checking completely',
      'unknown automatically parses JSON payloads into runtime records',
      'unknown executes faster at runtime than any',
    ],
    correctOptionIndex: 0,
    explanation: 'TypeScript forces developers to perform type checks or narrowing before accessing properties on an unknown type, preventing runtime property access errors.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_ts_02',
    skillId: 'skl_ts_react',
    difficulty: 'medium',
    questionText: 'In React 19, which hook is natively designed to access the value of an asynchronous action or resource directly inside render without repetitive useEffect states?',
    options: [
      'useMemo()',
      'use()',
      'useDeferredValue()',
      'useLayoutEffect()',
    ],
    correctOptionIndex: 1,
    explanation: 'The use() API in React allows reading the resolved value of Promises or context directly in components and integrates with Suspense.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_be_01',
    skillId: 'skl_node_express',
    difficulty: 'medium',
    questionText: 'In Express middleware pipelines, what happens if an error occurs inside an async handler without a try/catch or wrapper?',
    options: [
      'Express automatically catches it and formats a 500 response in Express 4 without any external handling',
      'It triggers an unhandled promise rejection that can crash the Node process or leave the request hanging',
      'It reroutes to the 404 handler immediately',
      'Node restarts the server instantly and retries the request',
    ],
    correctOptionIndex: 1,
    explanation: 'In Express 4, asynchronous errors must either be passed to next(err) explicitly or handled with an async handler wrapper.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_db_01',
    skillId: 'skl_db_sql',
    difficulty: 'medium',
    questionText: 'Which index type in PostgreSQL is best suited for equality and range queries on standard scalar types like integers and timestamps?',
    options: [
      'GIN (Generalized Inverted Index)',
      'B-Tree Index',
      'BRIN (Block Range Index)',
      'Hash Index',
    ],
    correctOptionIndex: 1,
    explanation: 'B-Tree is the default and most versatile index type in PostgreSQL, ideal for comparisons like <, <=, =, >=, and >.',
    source: 'curated',
    weight: 1.0,
  },
  {
    id: 'q_dsa_01',
    skillId: 'skl_dsa',
    difficulty: 'hard',
    questionText: 'What is the amortized time complexity of inserting n elements into a dynamic array (like JavaScript Array or Python list)?',
    options: [
      'O(n^2)',
      'O(n log n)',
      'O(n)',
      'O(1)',
    ],
    correctOptionIndex: 2,
    explanation: 'While an individual resize copy takes O(k), doubling capacity ensures each element is copied a constant number of times over n insertions, giving O(1) amortized per insert and O(n) total for n inserts.',
    source: 'curated',
    weight: 1.2,
  },
  {
    id: 'q_sys_01',
    skillId: 'skl_sys_design',
    difficulty: 'medium',
    questionText: 'Under the CAP theorem, what does a distributed system sacrifice when it prioritizes Consistency and Partition Tolerance (CP)?',
    options: [
      'Latency',
      'Availability (every non-failing node returns a non-error response)',
      'Durability',
      'Network security',
    ],
    correctOptionIndex: 1,
    explanation: 'During a network partition, a CP system rejects writes or returns errors to preserve consistency rather than returning stale data.',
    source: 'curated',
    weight: 1.0,
  },
];
